finalproject/sellbooks/buytextbooks/urls.py
from django.conf.urls import url
from . import views

app_name = "books"

urlpatterns = [
    #/buytextbooks/
    url(r'^$', views.home, name='home'),#views.index,name = 'index'

    #/buytextbooks/3(id)/
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name = 'detail'),

    #/buytextbooks/index.html/
    url(r'^index.html/', views.index, name='index'),


]

finalproject/sellbooks/sellbooks/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^buytextbooks/', include('buytextbooks.urls')),
]

finalproject/sellbooks/buytextbooks/models.py
from django.db import models

# Create your models here.

class Textbook(models.Model):
    textbooktitle = models.CharField(max_length=250)
    textbookauthor = models.CharField(max_length=250)
    textbookpublisher = models.CharField(max_length=250)
    textbooklocation = models.CharField(max_length=400)
    textbookimage = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.textbooktitle + ' - ' + self.textbookauthor

class Prepbook(models.Model):
    prepbooktitle = models.CharField(max_length=250)
    prepbookauthor = models.CharField(max_length=250)
    prepbookpublisher = models.CharField(max_length=250)
    prepbooklocation = models.CharField(max_length=400)
    prepbookimage = models.CharField(max_length=1000)

    def __str__(self):
        return self.prepbooktitle + ' - ' + self.prepbookauthor
    

finalproject/sellbooks/buytextbooks/views.py
from django.shortcuts import render,get_object_or_404
from .models import Textbook
from .models import Prepbook

# Create your views here.
def index(request):
    all_textbooks = Textbook.objects.all()
    all_prepbooks = Prepbook.objects.all()
    context = {
        'all_textbooks': all_textbooks,
        'all_prepbooks': all_prepbooks,
        }
    return render(request, 'buytextbooks/index.html', context)

def detail(request, book_id):
    textbook = get_object_or_404(Textbook, pk = book_id)
    prepbook = get_object_or_404(Prepbook, pk = book_id)
    return render(request, 'buytextbooks/detail.html', {'textbook': textbook,'prepbook': prepbook})

    
def home(request):
    return render(request, 'buytextbooks/testRun.html')

finalproject/sellbooks/buytextbooks/templates/buytextbooks/base.html
<!DOCTYPE html>
<html>
  <head>
	{% load staticfiles %}
	<link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
	<link rel="stylesheet"  type="text/css" href= {% static "buytextbooks/home.css" %} >
  		<title>Book Hook</title>

		<div style="float:right">
			<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
			<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>

    		<h1>Book Hook</h1>
  </head>
<!-- make a div or a nav tag for this-->
 	<ul>
	      <li><a class="active" href="{% url 'books:home' %}">Home</a></li>
	      <li><a class="active" href="{% url 'books:index' %}">Buy Textbooks</a></li>
	      <li><a class="active" href="{% url 'books:index' %}">Buy Prep Books</a></li>
	      <li><a class="active" href="sell.html">Sell Books</a></li>
	      <li><a class="active" href="blog.html">Blog</a></li>
	</ul>
<body>


</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/blog.html
<!DOCTYPE html>
<html>
	<head>
		<link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
	    <link rel="stylesheet"  href="home.css">
	</head>
	<title>Blog</title>
		<div style="float:right">
		<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
	<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 <h1>Boss Blog</h1>
<style>
img {
  display: block;
  width: 40%;
  margin: auto;
  }
}
body {
	font-family: 'Roboto', sans-serif;	
	}
h1 {
	text-align: center;
	font-family: 'Questrial', sans-serif;
	font-size: 50px;
	color: #666666;
	padding-left: 15px;
	}
</style>
	 <ul>
      <li><a href="home.html">Home</a></li>
      <li><a href="textbooks.html">Buy Textbooks</a></li>
      <li><a href="prepbooks.html">Buy Prep Books</a></li>
      <li><a href="sell.html">Sell Books</a></li>
      <li><a class="active" href="blog.html">Blog</a></li>
	</ul>
<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

<!-- Header -->
<header class="w3-container w3-center w3-padding-32"> 
</header>

<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l8 s12">
  <!-- Blog entry -->
  <div class="firstentry">
    <img src="http://img.talkandroid.com/uploads/2013/11/stack_of_books.jpg" alt="Books" style="width:80%">
    <div class="w3-container">
      <h3><b>Cool Summer Reads</b></h3>
      <h5>The Coolest Books of 2017 You Have to Try <span class="w3-opacity">August 3, 2017</span></h5>
    </div>

    <div class="w3-container">
      <p>
      <ol>
      <li>Carve the Mark by Veronica Roth</li>
      <li>City of Saints and Thieves by Natalie C.Andersen</li>
      <li>We Are Okay by Nina LaCour</li>
      <li>Camp So-and-So by Mary McCoy</li>
      </ol>
      </p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
        </div>
        <div class="w3-col m4 w3-hide-small">
        </div>
      </div>
    </div>
  </div>
  <hr>

  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
  <img src="http://pathct.org/wp-content/uploads/2016/09/backtoschool1.jpg" alt="Pencils" style="width:100%">
    <div class="w3-container">
      <h3><b>Back-to-School Checklist</b></h3>
      <h5>Are you Ready For School?, <span class="w3-opacity">August 3, 2017</span></h5>
    </div>

    <div class="w3-container">
      <p>
      As the summer wraps up, it's time to get ready for school! Check to see if you have all these materials:
      <ol>
      <li>At least 4-5 pencils</li>
      <li>2-3 pens (Black, Blue, Red)</li>
      <li>Highlighters</li>
      <li>Notebooks</li>
      <li>Binders/Portfolio/Folders</li>
      </ol>
      </p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
        </div>
        <div class="w3-col m4 w3-hide-small">
        </div>
      </div>
    </div>
  </div>
<!-- END BLOG ENTRIES -->
</div>

<!-- Introduction menu -->
<div class="w3-col l4">
  <!-- About Card -->
  <div class="w3-card-2 w3-margin w3-margin-top">
  <img src="" style="width:100%">
    <div class="w3-container w3-white">
      <h4><b>About Our Blog</b></h4>
      <p>Welcome to the coolest blog in the world: Boss Blog! We keep you up-to-date on almost everything from cool reads to school stuff to fun activities to try. We are constantly updating our material, so stay tuned for more cool stuff!</p>
    </div>
  </div><hr>
  
  
<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-light-green w3-padding-32 w3-margin-top">
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/detail.html
<img src="{{textbook.textbookimage}}">

<h1>{{textbook.textbooktitle}}</h1>
<h3>{{textbook.textbookauthor}}</h3>
<h3>{{textbook.textbookpublisher}}</h3>
<h3>{{textbook.textbooklocation}}</h3>

<img src="{{prepbook.prepbookimage}}">

<h1>{{prepbook.prepbooktitle}} </h1>
<h3>{{prepbook.prepbookauthor}}</h3>
<h3>{{prepbook.prepbookpublisher}}</h3>
<h3>{{prepbook.prepbooklocation}}</h3>


finalproject/sellbooks/buytextbooks/templates/buytextbooks/home.html
<!DOCTYPE html>
<html>
    <head>
	{% load staticfiles %}
	<link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
	<link rel="stylesheet"  type="text/css" href= {% static "buytextbooks/home.css" %} >
  		<title>Book Hook</title>

		<div style="float:right">
			<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
			<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>

    		<h1>Book Hook</h1>
    <style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
.search {
    background-color: #ABDB25;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

</style>
  </head>
  	<ul>
	      <!--<li><a class="active" href="home.html">Home</a></li>
	      <li><a href="textbooks.html">Buy Textbooks</a></li>
	      <li><a href="prepbooks.html">Buy Prep Books</a></li>
	      <li><a href="sell.html">Sell Books</a></li>
	      <li><a href="blog.html">Blog</a></li>-->
	
	      <li><a class="active" href="{% url 'books:home' %}">Home</a></li>
	      <li><a class="active" href="{% url 'books:index' %}">Buy Textbooks</a></li>
	      <li><a class="active" href="{% url 'books:index' %}">Buy Prep Books</a></li>
	      <li><a class="active" href="sell.html">Sell Books</a></li>
	      <li><a class="active" href="blog.html">Blog</a></li>
	</ul>
	
<body>

<h2>Search</h2>

<form action="textbooksbrowse.html" style="border:1px solid #ccc">
  <div class="container">
    <label><b>What kind of book would you like to buy?</b></label><br>
    <form action="">
    <input type="radio" name="typeofbook" value="textbook" > Textbook<br>
    <input type="radio" name="typeofbook" value="prepbook"> Prep Book<br><br>
    </form>
	<label><b>Title</b></label>
    <input type="text" placeholder="Enter Title" name="title" optional><br>
    <label><b>Subject</b></label>
    <input type="text" placeholder="Enter Subject" name="subject" optional>
    <label><b>Publisher</b></label> <br>
    <input type="text" placeholder="Name of Publisher" name="Publisher/Author" optional>
    <label><b>Author</b></label> <br>
    <input type="text" placeholder="Name of Author" name="Author" optional>
    <div class="clearfix">
      <input type="submit" class = "search" value="Search" > 
    </div>
  </div>
</form>

</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/index.html
{% if all_textbooks %}
  <h3>Here are all the Textbooks:</h3>
    <ul>
      {% for textbook in all_textbooks %}
        <li><a href = "{% url 'books:detail' textbook.id%}">{{textbook.textbooktitle}}</a></li>
      {% endfor %}
    </ul>



  <h3>Here are all the Prepbooks:</h3>
    <ul>
      {% for prepbook in all_prepbooks %}
        <li><a href = "{% url 'books:detail' prepbook.id%}">{{prepbook.prepbooktitle}}</a></li>
      {% endfor %}
    </ul>

{% endif %}

finalproject/sellbooks/buytextbooks/templates/buytextbooks/login.html
<!DOCTYPE html>
<html>
	<head>
		 <link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
		<link rel="stylesheet"  href="home.css">
		<title>Boop!</title>
		<div style="float:right">
		<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
	<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>
    <h1>Boop!</h1>
  <ul>
      <li><a class="active" href="home.html">Home</a></li>
      <li><a href="textbooks.html">Buy Textbooks</a></li>
      <li><a href="prepbooks.html">Buy Prep Books</a></li>
      <li><a href="sell.html">Sell Books</a></li>
      <li><a href="blog.html">Blog</a></li>
	</ul>
<body> 
</body>
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn,.signupbtn {
    float: left;
    width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
       width: 100%;
    }
}
</style>
<body>

<h2>Login</h2>


	<label><b>Username</b></label>
    <input type="text" placeholder="Enter a Username" name="username" 			required>
    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
	<input type="checkbox" checked="checked"> Remember me
    

    <div class="clearfix">
      <button type="submit" class="Loginbtn">Login</button>
    </div>
  </div>
</form>

</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/prepbooks.html
<!DOCTYPE html>
<html>
	<head>
		<style>
	/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}
/* Set a style for all buttons */
.search {
    background-color: #ABDB25;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}
.container {
    padding: 16px;
}	
	  </style>
		<link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
		<link rel="stylesheet"  href="home.css">
  	<title>Boop!</title>
		<div style="float:right">
		<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
	<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>
    <h1>Boop!</h1>
  </head>
  <ul>
      <li><a href="home.html">Home</a></li>
      <li><a href="textbooks.html">Buy Textbooks</a></li>
      <li><a class="active" href="prepbooks.html">Buy Prep Books</a></li>
      <li><a href="sell.html">Sell Books</a></li>
      <li><a href="blog.html">Blog</a></li>
	</ul>
  <body>
	  <h2> Search</h2>
<form action="prepbooksbrowse.html" style="border:1px solid #ccc">
  <div class="container">
   <label><b>Title</b></label>
    <input type="text" placeholder="Enter Title" name="title" optional><br>
    <label><b>Subject</b></label>
    <input type="text" placeholder="Enter Subject" name="subject" optional>
    <label><b>Publisher</b></label> <br>
    <input type="text" placeholder="Name of Publisher" name="Publisher/Author" optional>
    <label><b>Author</b></label> <br>
    <input type="text" placeholder="Name of Author" name="Author" optional>
	   <div class="clearfix">
	<input type="submit" class = "search" value="Search"> 
    </div>
  </div>
</form>
  </body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/prepbooksbrowse.html
<!DOCTYPE html>
<html>
<title>Blog</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
</style>
<body>

<!--CONTENT -->

<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px"> 

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      
      <!-- HYPERLINK TITLE -->
	<h3><a href="google.com">title</a></h3>
      
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/steak.jpg" alt="Steak" style="width:100%">
		<h3><a href="google.com">E</a></h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/cherries.jpg" alt="Cherries" style="width:100%">
	<h3><a href="google.com">title</a></h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
      <p>What else?</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/wine.jpg" alt="Pasta and Wine" style="width:100%">
	<h3><a href="google.com">TITLE</a></h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>
  
  <!-- Second Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center">
    <div class="w3-quarter">
      <img src="/w3images/popsicle.jpg" alt="Popsicle" style="width:100%">
      <h3>All I Need Is a Popsicle</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/salmon.jpg" alt="Salmon" style="width:100%">
      <h3>Salmon For Your Skin</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/croissant.jpg" alt="Croissant" style="width:100%">
      <h3>Le French</h3>
      <p>Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
 
</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/sell.html
<!DOCTYPE html>
<html>
	<head>
		<style>
	/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}
/* Set a style for all buttons */
button {
    background-color: #ABDB25;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}
.container {
    padding: 16px;
}
	  </style>
		<link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
		<link rel="stylesheet"  href="home.css">
		<script>function previewFile() {
  var preview = document.querySelector('img');
  var file    = document.querySelector('input[type=file]').files[0];
  var reader  = new FileReader();

  reader.addEventListener("load", function () {
    preview.src = reader.result;
  }, false);

  if (file) {
    reader.readAsDataURL(file);
  }
}
window.previewFile = previewFile;
</script>
	<title>Boop!</title>
		 <div style="float:right">
		<input type="button" onclick="location.href='login.html';" value="Login"/>
	<input type="button" onclick="location.href='signup.html';" value="Sign Up"/>
		</div>
    <h1>Boop!</h1>
  </head>
  <ul>
      <li><a href="home.html">Home</a></li>
      <li><a href="textbooks.html">Buy Textbooks</a></li>
      <li><a href="prepbooks.html">Buy Prep Books</a></li>
      <li><a class="active" href="sell.html">Sell Books</a></li>
      <li><a href="blog.html">Blog</a></li>
	</ul>
<!DOCTYPE html>
<html>

<body>

<h2>Sell Books</h2>
    <form action="/action_page.php" style="border:1px solid #ccc">
	     <div class="container">
    <label><b>What kind of book are you selling today?</b></label><br>
	<input type="radio" name="typebook" value="textbook"> Textbook<br>
    <input type="radio" name="typebook" value="prepbook"> Prepbook<br><br>
    </form>
  <label><b>Book Title</b></label>
    <input type="text" placeholder="Enter Book Title" name="booktitle" 			required>
  <label><b>Author</b></label>
  	<input type="text" placeholder="Enter Author Name" name="authorname" required>
  <label><b>Publisher</b></label>
  	<input type="text" placeholder="Enter Publisher Name" name="publisher" required>
  <label><b>Condition</b></label>
  	<form action="">
    <input type="radio" name="condition" value="new"> New<br>
    <input type="radio" name="condition" value="verygood"> Very Good<br>
    <input type="radio" name="condition" value="good"> Good<br>
    <input type="radio" name="condition" value="used"> Used<br><br>
    </form>
  <label><b>Location</b></label>
  	<input type="text" placeholder="Enter Location (City, State) " name="location" required>
  <label><b>Upload Photo</b></label><br><br>

<input type="file" onchange="window.previewFile()"><br>
<img src="" height="200" alt="Image preview...">

    <div class="clearfix">
      <button type="submit" class="submitbtn">Submit</button>
	    </div>
</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/signup.html
<!DOCTYPE html>
<html>
	<head>
		 <link href="https://fonts.googleapis.com/css?family=Questrial|Roboto" rel="stylesheet">
		<link rel="stylesheet"  href="home.css">
		<title>Boop!</title>
		<div style="float:right">
		<input type="button" class="login" onclick="location.href='login.html';" value="Login"/>
	<input type="button" class="login" onclick="location.href='signup.html';" value="Sign Up"/>
    <h1>Boop!</h1>
  <ul>
      <li><a class="active" href="home.html">Home</a></li>
      <li><a href="textbooks.html">Buy Textbooks</a></li>
      <li><a href="prepbooks.html">Buy Prep Books</a></li>
      <li><a href="sell.html">Sell Books</a></li>
      <li><a href="blog.html">Blog</a></li>
	</ul>
<body> 
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn,.signupbtn {
    float: left;
    width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
       width: 100%;
    }
}
</style>
<body>

<h2>Signup Form</h2>

<form action="/action_page.php" style="border:1px solid #ccc">
  <div class="container">
  	<label><b>First Name</b></label>
    <input type="text" placeholder="Enter First Name" name="First Name" required>
    <label><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name" name="Last Name" 			required>
    <label><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>
    
	<label><b>Username</b></label>
    <input type="text" placeholder="Enter a Username" name="username" 			required>
    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
    <input type="checkbox" checked="checked"> Remember me
    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

    <div class="clearfix">
     
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>

</body>
</html>

finalproject/sellbooks/buytextbooks/templates/buytextbooks/testRun.html

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet"  href="home.css">
	<title>Boop!</title>
	<div style="float:right">
	<input type="button" class = "login" onclick="location.href='login.html';" value="Login"/>
	<input type="button" class = "login" onclick="location.href='signup.html';" value="Sign Up"/>
	</div>
    <h1>Boop!</h1>
  </head>
  <ul>
      <li><a href="home.html">Home</a></li>
      <li><a class="active" href="textbooks.html">Buy Textbooks</a></li>
      <li><a href="prepbooks.html">Buy Prep Books</a></li>
      <li><a href="sell.html">Sell Books</a></li>
      <li><a href="blog.html">Blog</a></li>
	</ul>
  <body>

	  <h2>Search</h2>
<form action="/action_page.php" style="border:1px solid #ccc">
 <div class="container">
    <label><b>Title</b></label>
    <input type="text" placeholder="Enter title" name="title" optional><br>
    <label><b>Publisher</b></label>
    <input type="text" placeholder="Name of Publisher" name="Publisher" optional><br>
    <label><b>Author</b></label>
    <input type="text" placeholder="Name of Author" name="Author" optional><br>

    <div class="clearfix">
      <a href = "index.html"><button type="button" class="search">Search</button></a>

    </div>

  </div>

</form>
  </body>
</html>